//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Punonjes
    {
        public int id_punonjes { get; set; }
        public string emri { get; set; }
        public decimal paga_mujore { get; set; }
    }
}
