//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class salaryEntities : DbContext
    {
        public salaryEntities()
            : base("name=salaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ditet_e_punes> Ditet_e_punes { get; set; }
        public virtual DbSet<Pagesat_dit_specifike> Pagesat_dit_specifike { get; set; }
        public virtual DbSet<Datat_e_Festave_Zyrtare> Datat_e_Festave_Zyrtare { get; set; }
        public virtual DbSet<Punonjes> Punonjes { get; set; }
    }
}
